package	inc.glamdring.vtables;
/**
	*	User:	jim
	*	Date:	Sep	18,	2008
	*	Time:	3:31:01	AM
	*/
interface	_trait		{
				Class	getValueClass();
}

;
//                                 interface	$$Any						                                 extends	_trait, $narrow<Any,	_trait> {<$						                                 extends $narrow,	$$						                                 extends	Any,	$$$						                                 extends	Class<$$>	>	$$	$($	$,$$$	$$$);	}
//                                 interface	$$Cons						                                 extends	_trait, $narrow<Cons,	_trait> {<$						                                 extends $narrow,	$$						                                 extends	Cons,	$$$						                                 extends	Class<$$>	>	$$	$($	$,$$$	$$$);	}
//                                 interface	$$ConsPair						                                 extends	_trait, $narrow<ConsPair,	_trait> {<$						                                 extends $narrow,	$$						                                 extends	ConsPair,	$$$						                                 extends	Class<$$>	>	$$	$($	$,$$$	$$$);	}
//                                 interface	$$Sequence						                                 extends	_trait, $narrow<Sequence,	_trait> {<$						                                 extends $narrow,	$$						                                 extends	Sequence,	$$$						                                 extends	Class<$$>	>	$$	$($	$,$$$	$$$);	}
//                                 interface	$$Vector						                                 extends	_trait, $narrow<Vector,	_trait> {<$						                                 extends $narrow,	$$						                                 extends	Vector,	$$$						                                 extends	Class<$$>	>	$$	$($	$,$$$	$$$);	}
//                                 interface	$$List						                                 extends	_trait, $narrow<List,	_trait> {<$						                                 extends $narrow,	$$						                                 extends	List,	$$$						                                 extends	Class<$$>	>	$$	$($	$,$$$	$$$);	}
//                                 interface	$$String						                                 extends	_trait, $narrow<String,	_trait> {<$						                                 extends $narrow,	$$						                                 extends	String,	$$$						                                 extends	Class<$$>	>	$$	$($	$,$$$	$$$);	}
//                                 interface	$$Guid						                                 extends	_trait, $narrow<Guid,	_trait> {<$						                                 extends $narrow,	$$						                                 extends	Guid,	$$$						                                 extends	Class<$$>	>	$$	$($	$,$$$	$$$);	}
//                                 interface	$$HashtableIterator						                                 extends	_trait, $narrow<Iterator<Map.Entry<?,?>>,	_trait> {<$						                                 extends $narrow,	$$						                                 extends	Iterator<Map.Entry>,	$$$						                                 extends	Class<$$>	>	$$	$($	$,$$$	$$$);	}
//                                 interface	$$Keyhash						                                 extends	_trait, $narrow<Keyhash,	_trait> {<$						                                 extends $narrow,	$$						                                 extends	Keyhash,	$$$						                                 extends	Class<$$>	>	$$	$($	$,$$$	$$$);	}
//                                 interface	$$Lock						                                 extends	_trait, $narrow<Lock,	_trait> {<$						                                 extends $narrow,	$$						                                 extends	Lock,	$$$						                                 extends	Class<$$>	>	$$	$($	$,$$$	$$$);	}
//                                 interface	$$Semaphore						                                 extends	_trait, $narrow<Semaphore,	_trait> {<$						                                 extends $narrow,	$$						                                 extends	Semaphore,	$$$						                                 extends	Class<$$>	>	$$	$($	$,$$$	$$$);	}
//                                 interface	$$ReadWriteLock						                                 extends	_trait, $narrow<ReadWriteLock,	_trait> {<$						                                 extends $narrow,	$$						                                 extends	ReadWriteLock,	$$$						                                 extends	Class<$$>	>	$$	$($	$,$$$	$$$);	}
//                                 interface	$$Operator						                                 extends	_trait, $narrow<Operator,	_trait> {<$						                                 extends $narrow,	$$						                                 extends	Operator,	$$$						                                 extends	Class<$$>	>	$$	$($	$,$$$	$$$);	}
//                                 interface	$$Macro						                                 extends	_trait, $narrow<Macro,	_trait> {<$						                                 extends $narrow,	$$						                                 extends	Macro,	$$$						                                 extends	Class<$$>	>	$$	$($	$,$$$	$$$);	}
//                                 interface	$$Object						                                 extends	_trait, $narrow<Object,	_trait> {<$						                                 extends $narrow,	$$						                                 extends	Object,	$$$						                                 extends	Class<$$>	>	$$	$($	$,$$$	$$$);	}
//                                 interface	$$Package						                                 extends	_trait, $narrow<Package,	_trait> {<$						                                 extends $narrow,	$$						                                 extends	Package,	$$$						                                 extends	Class<$$>	>	$$	$($	$,$$$	$$$);	}
//                                 interface	$$Process						                                 extends	_trait, $narrow<Process,	_trait> {<$						                                 extends $narrow,	$$						                                 extends	Process,	$$$						                                 extends	Class<$$>	>	$$	$($	$,$$$	$$$);	}
//                                 interface	$$RegexPattern						                                 extends	_trait, $narrow<RegexPattern,	_trait> {<$						                                 extends $narrow,	$$						                                 extends	RegexPattern,	$$$						                                 extends	Class<$$>	>	$$	$($	$,$$$	$$$);	}
//                                 interface	$$Stream						                                 extends	_trait, $narrow<Stream,	_trait> {<$						                                 extends $narrow,	$$						                                 extends	Stream,	$$$						                                 extends	Class<$$>	>	$$	$($	$,$$$	$$$);	}
//                                 interface	$$SocketStream						                                 extends	_trait, $narrow<SocketStream,	_trait> {<$						                                 extends $narrow,	$$						                                 extends	SocketStream,	$$$						                                 extends	Class<$$>	>	$$	$($	$,$$$	$$$);	}
//                                 interface	$$BroadcastStream						                                 extends	_trait, $narrow<BroadcastStream,	_trait> {<$						                                 extends $narrow,	$$						                                 extends	BroadcastStream,	$$$						                                 extends	Class<$$>	>	$$	$($	$,$$$	$$$);	}
//                                 interface	$$OutputBinaryStream						                                 extends	_trait, $narrow<OutputBinaryStream,	_trait> {<$						                                 extends $narrow,	$$						                                 extends	OutputBinaryStream,	$$$						                                 extends	Class<$$>	>	$$	$($	$,$$$	$$$);	}
//                                 interface	$$OutputTextStream						                                 extends	_trait, $narrow<OutputTextStream,	_trait> {<$						                                 extends $narrow,	$$						                                 extends	OutputTextStream,	$$$						                                 extends	Class<$$>	>	$$	$($	$,$$$	$$$);	}
//                                 interface	$$InOutBinaryStream						                                 extends	_trait, $narrow<InOutBinaryStream,	_trait> {<$						                                 extends $narrow,	$$						                                 extends	InOutBinaryStream,	$$$						                                 extends	Class<$$>	>	$$	$($	$,$$$	$$$);	}
//                                 interface	$$InOutTextStream						                                 extends	_trait, $narrow<InOutTextStream,	_trait> {<$						                                 extends $narrow,	$$						                                 extends	InOutTextStream,	$$$						                                 extends	Class<$$>	>	$$	$($	$,$$$	$$$);	}
//                                 interface	$$InputBinaryStream						                                 extends	_trait, $narrow<InputBinaryStream,	_trait> {<$						                                 extends $narrow,	$$						                                 extends	InputBinaryStream,	$$$						                                 extends	Class<$$>	>	$$	$($	$,$$$	$$$);	}
//                                 interface	$$InputTextStream						                                 extends	_trait, $narrow<InputTextStream,	_trait> {<$						                                 extends $narrow,	$$						                                 extends	InputTextStream,	$$$						                                 extends	Class<$$>	>	$$	$($	$,$$$	$$$);	}
//                                 interface	$$Struct						                                 extends	_trait, $narrow<Struct,	_trait> {<$						                                 extends $narrow,	$$						                                 extends	Struct,	$$$						                                 extends	Class<$$>	>	$$	$($	$,$$$	$$$);	}
//                                 interface	$$Symbol						                                 extends	_trait, $narrow<Symbol,	_trait> {<$						                                 extends $narrow,	$$						                                 extends	Symbol,	$$$						                                 extends	Class<$$>	>	$$	$($	$,$$$	$$$);	}
//                                 interface	$$SynonymStream						                                 extends	_trait, $narrow<SynonymStream,	_trait> {<$						                                 extends $narrow,	$$						                                 extends	SynonymStream,	$$$						                                 extends	Class<$$>	>	$$	$($	$,$$$	$$$);	}
//                                 interface	$$Number						                                 extends	_trait, $narrow<Number,	_trait> {<$						                                 extends $narrow,	$$						                                 extends	Number,	$$$						                                 extends	Class<$$>	>	$$	$($	$,$$$	$$$);	}
//                                 interface	$$Float						                                 extends	_trait, $narrow<Float,	_trait> {<$						                                 extends $narrow,	$$						                                 extends	Float,	$$$						                                 extends	Class<$$>	>	$$	$($	$,$$$	$$$);	}
//                                 interface	$$Double						                                 extends	_trait, $narrow<Double,	_trait> {<$						                                 extends $narrow,	$$						                                 extends	Double,	$$$						                                 extends	Class<$$>	>	$$	$($	$,$$$	$$$);	}
//                                 interface	$$DoubleFloat						                                 extends	_trait, $narrow<DoubleFloat,	_trait> {<$						                                 extends $narrow,	$$						                                 extends	DoubleFloat,	$$$						                                 extends	Class<$$>	>	$$	$($	$,$$$	$$$);	}
//                                 interface	$$Integer						                                 extends	_trait, $narrow<Integer,	_trait> {<$						                                 extends $narrow,	$$						                                 extends	Integer,	$$$						                                 extends	Class<$$>	>	$$	$($	$,$$$	$$$);	}
//                                 interface	$$Boolean						                                 extends	_trait, $narrow<Boolean,	_trait> {<$						                                 extends $narrow,	$$						                                 extends	Boolean,	$$$						                                 extends	Class<$$>	>	$$	$($	$,$$$	$$$);	}
//                                 interface	$$Character						                                 extends	_trait, $narrow<Character,	_trait> {<$						                                 extends $narrow,	$$						                                 extends	Character,	$$$						                                 extends	Class<$$>	>	$$	$($	$,$$$	$$$);	}
//                                 interface	$$Char						                                 extends	_trait, $narrow<Character,	_trait> {<$						                                 extends $narrow,	$$						                                 extends	Character,	$$$						                                 extends	Class<$$>	>	$$	$($	$,$$$	$$$);	}
//                                 interface	$$Int						                                 extends	_trait, $narrow<Integer,	_trait> {<$						                                 extends $narrow,	$$						                                 extends	Integer,	$$$						                                 extends	Class<$$>	>	$$	$($	$,$$$	$$$);	}
//                                 interface	$$Long						                                 extends	_trait, $narrow<Long,	_trait> {<$						                                 extends $narrow,	$$						                                 extends	Long,	$$$						                                 extends	Class<$$>	>	$$	$($	$,$$$	$$$);	}
//                                 interface	$$Function						                                 extends	_trait, $narrow<Function,	_trait> {<$						                                 extends $narrow,	$$						                                 extends	Function,	$$$						                                 extends	Class<$$>	>	$$	$($	$,$$$	$$$);	}
//                                 interface	$$CompiledFunction						                                 extends	_trait, $narrow<CompiledFunction,	_trait> {<$						                                 extends $narrow,	$$						                                 extends	CompiledFunction,	$$$						                                 extends	Class<$$>	>	$$	$($	$,$$$	$$$);	}
//                                 interface	$$Nil						                                 extends	_trait, $narrow<Nil,	_trait> {<$						                                 extends $narrow,	$$						                                 extends	Nil,	$$$						                                 extends	Class<$$>	>	$$	$($	$,$$$	$$$);	}
